title: Toilamba Blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hoang Phan # add your name
author-img: hoangphan-avatar.jpg # add your photo
about-author: Experienced Business Analyst with 1+ years of experience analyzing, solves problems, and give the solutions for the customers across travel and news fields. # add description
# social-twitter: # add your Twitter handle
social-facebook: hoangpm96 # add your Facebook handle
social-github: hoangpm96 # add your Github handle
social-linkedin: hoangphan96 # add your Linkedin handle
social-email: hoangpm.qn96@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
