title: Toilamba Blog
description: > # this means to ignore newlines until "baseurl:"
  Blog của Hoàng Phan, một Junior IT Business Analyst. Blog chia sẻ những kiến thức bổ ích liên quan đến IT BA và QC.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hoang Phan # add your name
author-img: hoangphan-avatar.jpg # add your photo
about-author: Mình là Hoàng - một Junior IT Business Analyst. Blog mình sẽ đi từ những cái mình học được từ công việc, và chia sẻ những kiến thức mình đã có đến mọi người trên blog, cũng như mong nhận được feedback từ những anh chị bạn khác, giúp bản thân mình improve hơn. # add description
# social-twitter: # add your Twitter handle
social-facebook: hoangpm96 # add your Facebook handle
social-github: hoangpm96 # add your Github handle
social-linkedin: hoangphan96 # add your Linkedin handle
social-email: hoangpm.qn96@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
